"""initial_tables

Revision ID: c91f94756ab9
Revises: 
Create Date: 2026-10-01 18:07:19.756472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91f94756ab9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('secret', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_endpoints_name', 'webhook_endpoints', ['name'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='e.g. payment.created, order.fulfilled'),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'SUCCESS', 'FAILED', 'RETRYING', name='event_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_endpoint_id', 'webhook_events', ['endpoint_id'], unique=False)
    op.create_index('ix_webhook_events_endpoint_status', 'webhook_events', ['endpoint_id', 'status'], unique=False)
    op.create_index('ix_webhook_events_received_at', 'webhook_events', ['received_at'], unique=False)
    op.create_index('ix_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.create_table('webhook_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='SUCCESS or FAILED'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_attempts_event_id', 'webhook_attempts', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_attempts_event_id', table_name='webhook_attempts')
    op.drop_table('webhook_attempts')
    op.drop_index('ix_webhook_events_status', table_name='webhook_events')
    op.drop_index('ix_webhook_events_received_at', table_name='webhook_events')
    op.drop_index('ix_webhook_events_endpoint_status', table_name='webhook_events')
    op.drop_index('ix_webhook_events_endpoint_id', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_webhook_endpoints_name', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    # ### end Alembic commands ###